import { Inter } from "next/font/google";

import "./globals.css";
import { FormProvider } from "./components/FormContext";

const inter = Inter({ subsets: ["latin"], weights: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <FormProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </FormProvider>
  );
}
